version: "3.7"
services:
  pg:
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "dmhy_indexer"

  main:
    build: .
    cap_add:
      - SYS_ADMIN  # ref https://github.com/GoogleChrome/puppeteer/blob/v1.12.1/docs/troubleshooting.md#running-puppeteer-in-docker 
    image: "indexer"
    command: yarn start
    environment:
      INDEXER_MODE: "dmhy"
      DB_HOST: "pg"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_NAME: "dmhy_indexer"
      DB_PASS: "123456"
    volumes:
      - ".:/irohalab/indexer"
      - "/irohalab/indexer/node_modules"
    depends_on:
      - pg
