version: "3.7"
services:
  pg:
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DB_USER-postgres}"
      POSTGRES_PASSWORD: "${DB_PASS-123456}"
      POSTGRES_DB: "${DB_NAME-dmhy_indexer}"

  main:
    build: .
    cap_add:
      - SYS_ADMIN  # ref https://github.com/GoogleChrome/puppeteer/blob/v1.12.1/docs/troubleshooting.md#running-puppeteer-in-docker 
    image: "indexer"
    command: yarn start
    ports:
      - "9229:9229"
    environment:
      INDEXER_MODE: "${INDEXER_MODE-dmhy}"
      DB_HOST: "${DB_HOST-pg}"
      DB_PORT: "${DB_PORT-5432}"
      DB_USER: "${DB_USER-postgres}"
      DB_NAME: "${DB_NAME-dmhy_indexer}"
      DB_PASS: "${DB_PASS-123456}"
    volumes:
      - ".:/irohalab/indexer"
      - "/irohalab/indexer/node_modules"
      - "/irohalab/indexer/dist"
    depends_on:
      - pg
